### ISSUE TITLE
How would you feel about tilde auto-expansion being a built-in optional setting in Clink?

### ISSUE THREAD

**Issue by chrisant996** [HeyItsJono/HomeClink#1]
@HeyItsJono How would you feel about similar auto-expand being built into Clink?

Recent improvements in the Clink API have made it possible to do a good and clean job of auto-expanding tildes.  I have a script that I'm considering building into Clink.  It is also able to apply configurable colors to tildes that will auto-expand, and to tilde escape sequences (and the tilde escape sequence is configurable).

(And I'm torn between making it default to on versus default to off -- there are good reasons for either to be the default.)

**Comment by HeyItsJono** [comment]
This would be amazing, I would be super keen! I feel like it should default to whatever is safest, I recall you saying readline tilde expansion had its caveats and could produce unexpected behavior occasionally, if that would be the case with this then probably best to make it something users explicitly turn on so they are more clued in if things occasionally don't work as expected.

**Comment by chrisant996** [comment]
Agreed.

**Comment by chrisant996** [comment]
The main reason I'm interested to build it into Clink is so that it can work with input line coloring for the command word.

E.g. `~\foo.exe` display in the recognized-executable color if the program file exists.

I'm still considering other options, and it might not get built in.  E.g. API enhancements that benefit other scripts as well.  But if it doesn't get built in, then I'll at least share a cool upgraded script (including coloring which tildes will auto expand, and which escaped tildes will turn into single tildes, and configurable escape sequence for tilde, and maybe even a key binding to toggle tilde auto expand on/off).

**Comment by chrisant996** [comment]
Instead of building it in, I added a new API in Clink v1.3.38 so that a tilde-expand script -- and also other scripts -- can affect how the executable file detection/coloring works (e.g. if you want to launch a document such as `~\documents\my_taxes.xlsx`).

I've added my `tilde_autoexpand.lua` script to the [clink-gizmos](https://github.com/chrisant996/clink-gizmos) repo.

The script correctly respects quotes, and correctly respects word boundaries (using `rl.expandtilde(escaped_input, true)` doesn't respect either properly, just like Readline's `tilde-expand` command doesn't).

The script has 4 settings:

- `tilde.autoexpand` (default is false) -- controls whether tilde are auto-expanded in the command line, according to proper tilde syntax and word boundaries.
- `tilde.escape` (default is `~~`) -- a substring that is auto-replaced by a single tilde (you could configure it to `|~` to match HomeClink).
- `color.autoexpandtilde` (default is `bright cyan`) -- a color used to highlight any tildes that will be auto-expanded (can set it to an empty string to disable the highlight).
- `color.escapetilde` (default is `bright magenta`) -- a color used to highlight any `tilde.escape` substrings that will be auto-replaced by a single tilde (can set it to an empty string to disable the highlight).

**Comment by chrisant996** [comment]
@HeyItsJono Clink v1.3.38 is released, and the `tilde_autoexpand.lua` script in [clink-gizmos](https://github.com/chrisant996/clink-gizmos) has some enhancements that may interest you.  See previous for details.
